### ISSUE TITLE
replace Session Storage and Local Storage drivers with Web Storage driver

### ISSUE THREAD

**Issue by thecotne** [unjs/unstorage#203]
### Describe the feature

session and locale storage is really same kind of storage so it does not make sense to have two separate drivers for them 

see 
- https://developer.mozilla.org/en-US/docs/Web/API/Storage
- https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API

it's also one interface in typescript for both objects

- https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts#L21520
- https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts#L25709
- https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.generated.d.ts#L25758

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
You are right. PR welcome to introduce a single new driver. We can reexport it as local/session storage for ease of use and bw compatibility.

**Comment by pi0** [comment]
The term "web" storage is less known and might be confusing in unstorage drivers since we list browser specific drivers in a page (+indexdb) ++ unstorage interface itself is loosly based on same interface.

With refactor, localstorage driver is basically same but only a more known name.

If you have any ideas for another name that is more clear we can do it in v2.

**Comment by pi0** [comment]
Thanks again for your time ❤️ , sorry the review just got delayed and some changes stalled in there, otherwise, I would have commented or applied to refactor on yours... The main idea of refactoring them to one impl was the main point for me. 

Web Storage abstraction term in the context of MDN docs and standards is totally fine but as an unstorage driver name could be confusing IMO + the fact that abstracted driver is not usable, only available Web Storage _instances_ (localStorage or sessionStorage) are.
