### ISSUE TITLE
HTTP driver bug

### ISSUE THREAD

**Issue by olivbau** [unjs/unstorage#268]
### Environment

windows
node v18.16.0

### Reproduction

Run a http driver

### Describe the bug

http driver seems to return a string `"null"` on getItem when item is missing, instead of a "real" `null` object

**Comment by itpropro** [comment]
I couldn't reproduce this @olivbau, but added some tests for null checks in #365. You should also note that adding a string `"null"` as a value will result in a null object as return. This is due to JSON parsing with destr, which behaves exactly as `JSON.pase` in this matter.
Feel free to reopen with a reproduction, if this still happens for you.
