### ISSUE TITLE
Use Cloudflare KV native meta

### ISSUE THREAD

**Issue by pi0** [unjs/unstorage#32]
https://developers.cloudflare.com/workers/runtime-apis/kv#metadata

By using native meta, we can allow expiration. (depends on #13)

**Comment by Hebilicious** [comment]
We should be able to grab the 3rd parameter from `.setItem` and pass it to cloudflare KV :

- For [HTTP single](https://developers.cloudflare.com/api/operations/workers-kv-namespace-write-key-value-pair-with-metadata)
- For [HTTP batch](https://developers.cloudflare.com/api/operations/workers-kv-namespace-write-multiple-key-value-pairs)

The single version is poorly documented, but I assume it works if you pass the same options in the body. Otherwise we can just modify the HTTP driver to use the batch API.

```json
  {
    "base64": false,
    "expiration": 1578435000,
    "expiration_ttl": 300,
    "key": "My-Key",
    "metadata": {
      "someMetadataKey": "someMetadataValue"
    },
    "value": "Some string"
  }
  ```
  
  ... ie we should be able to do : 
  
  ```ts
  await storage.setItem("My-Key", "Some string", { expiration: 1578435000, expiration_ttl: 300, base64: false, metadata: {someMetadataKey: "someMetadataValue"}} );
  ```
  and get the query above sent properly.

**Comment by matfire** [comment]
I've just started working on a project using unstorage and kind of need this feature. If nobody is working on it, can work on implementing this ?
I'd rather modify it to use the batch endpoint since it handles expiration_ttl directly. If using the single put method, we'd still need to do a request before that to check the metadata for an expiration date, right ?

The only issue I can see in this is that the naming convention for the binding and http API is not the same (`expirationTtl` for binding, `expiration_ttl` for the API), so we'd probably need to abstract it and convert it back to right format (i.e. check for a parameter called `ttl` and handle that internally)

Please let me know if I can help :)

**Comment by matfire** [comment]
Hello, would love to work on this if nothing is currently happening
