### ISSUE TITLE
refactor: use cloudflare SDK

### ISSUE THREAD

**Issue by oritwoen** [unjs/unstorage#420]
### Describe the feature

Cloudflare recently released its own official TypeScript SDK.

According to README.md itself and the `Requirements` section, Nitro and environments for UnJS are supported.

It would make sense to refactor the currently used fetch into the official SDK.

- https://github.com/cloudflare/cloudflare-typescript

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for the suggestion. Using an SDK would reduce the maintenance burden but this SDK, however, works, is too big [^1] [^2], and from implementation at least I can understand with classes it is not a tree-shakable thing. Also the shims, even [node shim](https://unpkg.com/browse/cloudflare@3.0.0/_shims/node-runtime.mjs) depend on unbundled `node-fetch` which we are going to completely drop soon across the ecosystem.

I wish someday we can consider it but currently, it is really far from this state and since v3 is recently releases with this structure, I'm not sure how much upstream is flexible to major changes..

[^1]: https://bundlephobia.com/package/cloudflare@3.0.0
[^2]: https://bundlejs.com/?q=cloudflare%403.0.0
