### ISSUE TITLE
setItemRaw with the fsDriver doesn't writeFile with binary encoding

### ISSUE THREAD

**Issue by mxrlkn** [unjs/unstorage#482]
### Environment

Version 1.12.0
Node 21

### Reproduction

Server:
```
import {createStorageServer} from "unstorage/server";
import fsDriver from "unstorage/drivers/fs";
import {createStorage} from "unstorage";

const server = createStorageServer(
	createStorage({driver: fsDriver({base: "/data"})}),
);
```

Client:
```
import httpDriver from "unstorage/drivers/http";
import {createStorage} from "unstorage";

const storage = createStorage({
	driver: httpDriver({base: "https://example.com"}),
});

storage.setItemRaw(`file.zip`, ZIP_FILE_BUFFER);
```

### Describe the bug

When using `setItemRaw` with the fsDriver, I'd assume it would set the encoding to `binary` but it doesn't:
https://github.com/unjs/unstorage/blob/3e9c49982f39e088a74226e39f5a8a384b8c96d0/src/drivers/fs.ts#L83

That means that `writeFile` defaults to utf8 here:
https://github.com/unjs/unstorage/blob/3e9c49982f39e088a74226e39f5a8a384b8c96d0/src/drivers/utils/node-fs.ts#L19

because of this, I can't for example, open this zip file on the file system.

Is there any reason it can't be changed to `binary` for `setItemRaw`:
`return writeFile(r(key), value, "binary");`

**Comment by pi0** [comment]
In node.js fs API, when `data` is a Buffer, encoding will be ignored that's why we don't set it.

In addition to [tests](https://github.com/unjs/unstorage/blob/3e9c49982f39e088a74226e39f5a8a384b8c96d0/test/server.test.ts#L72), I have made [another sandbox](https://stackblitz.com/edit/stackblitz-starters-dwdqr) that confirms with the above scenario (zip over HTTP server) the zip format is valid. I have also verified it locally and the zip format is valid.

In order to further investigate you issue:
- Please make sure using latest unstorage version by recreating lockfile
- If you are using a different scenrio, it would be nice if you can either fork above sandbox to reproduce or share more info

**Comment by mxrlkn** [comment]
I just did a retest of my scenario, and now it works... I tried it many times yesterday, before making the issue.

For future reference, this is my code to create the zip:

```js
const zip = `${version}.zip`;

const file = await execa("zip", ["-r", zip, "dist"]).then(async () => {
	const f = await readFile(zip);
	await rm(zip);
	return f;
});

await storage.setItemRaw(zip, file);
```
I'm using docker with a volume mount on MacOS, maybe there was an I/O issue that corrupted my file? maybe the zip command silently fails? I have no idea honestly.

Thank you for creating the sandbox so fast and looking into it. I appreciate it.
