### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by justindasilva** [unjs/unstorage#50]
Firstly, my IDE doesn't seem to find `unstorage/drivers/fs` and is being underlined in red.
![Screen Shot 2022-05-06 at 3 06 51 PM](https://user-images.githubusercontent.com/882534/167202201-933ae212-f648-46f7-a53f-3e89b46a4f4f.png)
Note that I'm using the FS driver just fine, so not sure why it's throwing an error.

Secondly, the code below works just fine and I'm able to set an Array in the storage, but Typescript is complaining in this case since the type returned is `StorageValue`. 
![Screen Shot 2022-05-06 at 3 05 59 PM](https://user-images.githubusercontent.com/882534/167202450-37eeea20-5e05-4e6a-9da4-ba68584562aa.png)
What should I do in this case so that Typescript doesn't complain.

**Comment by xSuffix** [comment]
I also have the problem that VS Code cannot find the fs driver module, haven't found a solution yet.

Regarding your second problem:
You initialize `items` as an array but then assign it a value of type StorageValue.

I don't have much TS experience so maybe there is a cleaner solution but those work for me:

1. If you don't need `items` to be an array, you could initialize it as type any or StorageValue:
```javascript
let items

if (await storage.hasItem('items'))
  items = await storage.getItem('items')
```

2. If you need it to be an array (which it isn't by default, I got either an object or a string), you can convert it to an array like this:
```javascript
async function storageToArray(item: string) {
  const storageValue = await storage.getItem(item)

  if (storageValue == null)
    return []

  if (typeof storageValue === 'string' || storageValue instanceof String)
    return [storageValue]

  if (typeof storageValue === 'number' || storageValue instanceof Number)
    return [storageValue]

  if (typeof storageValue === 'boolean' || storageValue instanceof Boolean)
    return [storageValue]

  return Object.values(storageValue)
}
```
I do not check for `hasItem()` because if it doesn't, `getItem()` should return null, which has to be handled anyway.

**Comment by pi0** [comment]
Thanks for the feedbacks. Type issues with drivers and array should be fixed in next release. Feel free to open new issues (individually) if anything else is not working as expected.
